services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5182:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=http://localhost:5182
    networks:
      - mybp-network

networks:
  mybp-network:
    driver: bridge
